Alain Lernjournal
=================
Alain Keller
Version 1.0, 31.05.2016
:toc:

= Ablauf
In diesem Modul geht es darum eine Applikation nach einem gegebenen Pflichtenheft zu implementieren. Gemäss dem Skript machten wir am Anfang CRC-Karten. Diese beschreiben die Klassen, deren Aufgaben und beziehungen. Danach prüftn wir anhand von Use-Cases, ob wir alles berücksichtigt haben. Meiner Meinung nach macht es mehr Sinn, wenn man zuerst die Use-Cases erstellt und anhand diesen die Klassen bestimmt. Von deren Beschreibungen kann man auch anhand der Verben und Nomen Klassen und Methoden ableiten. Diese werden dann mit einem Klassendiagramm dargestellt. Einzelne Use-Cases können auc in Sequenzdiagrammen dargestellt werden. Ich denke diese Methode wöre effizienter in der Umsetzung, da man einen Zwischenschritt auslässt. 

= Darstellung und Filter
Wir waren uns Anfangs nicht einig, wie wir das Programm im GUI darsetllen möchten, dass auch das User Experience gewährleistet ist. Pascal hatte die Idee ein Docking Framework auszuprobieren. Dies ermöglicht es uns verschiedene Module zu machen. Diese kann man dann wie in VisulaStudio herumschieben und an verschiedenen Punkten andocken. In diesem Projekt habe ich zum ersten Mal mit Styles gearbeitet. Dabei gibt man im App.xmal die verschiedenen Eigenschaften wie z.B. die Grösse, oder ein Hintergrundbild, an. Nun kann man den Style allen Elementen in den Views hinzufügen. Somit ist ein einheitliches Design, wie in userem Fall bei den Add und Remove-Buttons, einfach gelöst. Muss man etwas ändern, braucht man die Änderung nur an einem Ort zu machen. 


= Serializierung
Wir haben uns entschieden die Daten nicht in einer Datenbank abzuspeichern, damit wir geung Zeit zum Implementieren der Kinoverwaltung haben. Deshalb speichern wir die Daten mit Hilfe der Serialisierung in XML-Dateien ab. Über das Serializable Attribut in C# ist das relativ einfach gelöst. Man muss nur sagen wann und wo es gespeichert werden muss, und von wo es beim Start der Applikation die Daten er holt. Somit konnten wir uns viel Zeit sparen, wleche wir sonst für das Datenmodell, die DB aufsetzen und DB-Anbidung gebraucht hätten. Die Daten werden in .satanData dateien gespeichert.

= Guthub
Da Seraphin sein GIT bei sich falsch konfiguriert hatte, gab es Probleme mit den Grafiken. Dies löste Pascal indem er die GIT-History umschrieb. Das hatte jedoch zur Folge, dass bei jedem von uns die lokale History nicht mit der Online-History übereinstimmte, und es zu Merge-Problemen kam. Um dies zu lösen, mussten wir den Origin-Master fetchen und danach einen Hard Pull machen. 

= Fazit
In deisem Projekt habe ich viele Erfarungen mit Frmaeworks gemacht. Dazu gehörte vor allem das Benutzen von schon vorhandenen Klassen und Methoden. Auch im erstellen von Views habe ich Fortschritte gemacht.

