Alain Lernjournal
=================
Alain Keller
Version 1.0, 31.05.2016
:toc:

= Ablauf
In diesem Modul geht es darum eine Applikation nach einem gegebenen Pflichtenheft zu implementieren. Gemäss dem Skript machten wir am Anfang CRC-Karten. Diese beschreiben die Klassen, deren Aufgaben und beziehungen. Danach prüftn wir anhand von Use-Cases, ob wir alles berücksichtigt haben. Meiner Meinung nach macht es mehr Sinn, wenn man zuerst die Use-Cases erstellt und anhand diesen die Klassen bestimmt. Von deren Beschreibungen kann man auch anhand der Verben und Nomen Klassen und Methoden ableiten. Diese werden dann mit einem Klassendiagramm dargestellt. Einzelne Use-Cases können auc in Sequenzdiagrammen dargestellt werden. Ich denke diese Methode wöre effizienter in der Umsetzung, da man einen Zwischenschritt auslässt. 

= Darstellung und Filter
Wir waren uns Anfangs nicht einig, wie wir das Programm im GUI darsetllen möchten, dass auch das User Experience gewährleistet ist. 


= Serializierung
Wir haben uns entschieden die Daten nicht in einer Datenbank abzuspeuchern, damit wir geung Zeit zum Implementieren der Kinoverwaltung haben. Deshalb speichern wir die Daten mit Hilfe der Serialisierung in XML-Dateien ab. Über das Serializable Attribut in C# ist das relativ einfach gelöst. Man muss nur sagen wann und wo es gespeichert werden muss, und von wo es beim Start der Applikation die Daten er holt. Somit konnten wir uns viel Zeit sparen, wleche wir sonst für das Datenmodell, die DB aufsetzen und DB-Anbidung gebraucht hätten. 