Dokumentation
=============
Alain Keller, Pascal Honegger und Seraphin Rihm
Version 1.1, 24.05.2016
:toc:

== Framework

=== C#
Wir werden C#6 / .Net 4.6.1 verwenden. Das Projekt wird als WPF-Applikation umgesetzt.

== Datenstruktur

=== Aufbau des Projektordner
Die Dateien werden in verschiedene Ordner (Namespaces) unterteilt. Diese werden nach Überthemen des Projektes geordnet. Die Ordner sind doppelt vorhanden, einmal im Haupt-Projekt und einmal im Test-Projekt.

== Continous Integration
link:https://ci.appveyor.com/project/PascalHonegger/kinoverwaltung[AppVeyor] unterstützt als einzige CI neben Travis C#, benötigt aber weniger Konfigurationen (One-Click-Setup).

== VCS-Server
=== link:https://github.com/StarlordTheCoder/KinoVerwaltung[Client]
C#-WPF-Client. Verantwortlich für die Darstellung und das Verwalten der Daten.

== Pflichtenheft

=== Anforderungen

* Kino
** Das Tool kann mehrere Kinos verwalten
** Kinos können erstellt, bearbeitet und ausgewählt werden

* Saal
** Es können Säle erstellt, angesehen und bearbeitet werden
** Verfügt über mehrere Sitze und Reihen

* Sitzplatz
** Kann auch ein Spezial-Sitz sein
*** Möglicher Preiszuschlag
*** Eventuell mehr als eine Person pro Sitzplatz (Sofa)
** Wird im GUI dargestellt

* Film
** Es können Filme erstellt, angesehen und bearbeitet werden
** Ein Film hat ein Cover und einen optionalen Trailer-Link

* Filter
** Der Anwender kann in der Applikation diverse Daten suchen / filtern
*** Benutzerkonto
*** Film
*** Aufführung
*** Reservierung
** Diese Filter sind eng verbunden
*** Der Anwender muss in der Lage sein, anhand seines ausgewählten Filmes im "Film suchen" die Darstellung des "Aufführung suchen" anzupassen

== Konzepte

=== Filter
Um die Daten der Kinoverwaltung zu filtern, entschieden wir uns dafür, dass jedes Modul seine eigene Filter besizt. Damit die Filter im Code zentral verwaltet werden können, machten wir diese generisch. Dort haben wir drei Grundfilter, einen DateFilter, StringFilter und einen ComplexFilter. Wobei letzterer nach Werten von anderen Modulen filtern kann. Dies ist nötig, wenn man die Reservationen einer Person von einem bestimmen FIlm ansehen will. Die Module können nun über den FilterConfigurator ihren Filter konfigurieren. Sie können zum Beispiel einen Stringfilter für den Filmnamen und einen DateFilter für das Präsentationsdatum anfordern. Dem Filter wird zusätzlich die Liste mit den zu filternden Daten mitgegeben. Beim ComplexFilter wird angegeben nach welcher Liste im anderen Modul gefiltert werden muss. Zusätzlich wird angegeben welche Liste im eigenen Modul den werten des anderen Modules entsprechen müssen. Der Filter und die Liste können im GUI angezeigt werden. 
