Dokumentation
=============
Alain Keller, Pascal Honegger und Seraphin Rihm
Version 1.1, 24.05.2016
:toc:

== Framework

=== C#
Wir werden C#6 / .Net 4.6.1 verwenden. Das Projekt wird als WPF-Applikation umgesetzt.

== Datenstruktur

=== Aufbau des Projektordner
Die Dateien werden in verschiedene Ordner (Namespaces) unterteilt. Diese werden nach Überthemen des Projektes geordnet. Die Ordner sind doppelt vorhanden, einmal im Haupt-Projekt und einmal im Test-Projekt.

== Continous Integration
link:https://ci.appveyor.com/project/PascalHonegger/kinoverwaltung[AppVeyor] unterstützt als einzige CI neben Travis C#, benötigt aber weniger Konfigurationen (One-Click-Setup).

== VCS-Server
=== link:https://github.com/StarlordTheCoder/KinoVerwaltung[Client]
C#-WPF-Client. Verantwortlich für die Darstellung und das Verwalten der Daten.

== Pflichtenheft

=== Anforderungen

* Kino
** Das Tool kann mehrere Kinos verwalten
** Kinos können erstellt, bearbeitet und ausgewählt werden

* Saal
** Es können Säle erstellt, angesehen und bearbeitet werden
** Verfügt über mehrere Sitze und Reihen
** Sitze werden graphisch dargestellt

* Sitzplatz
** Kann auch ein Spezial-Sitz sein (Sitzarten)
*** Möglicher Preiszuschlag
*** Eventuell mehr als eine Person pro Sitzplatz (Sofa)
** Wird im GUI dargestellt

* Film
** Es können Filme erstellt, angesehen und bearbeitet werden

* Filter
** Der Anwender kann in der Applikation diverse Daten suchen / filtern
*** Benutzerkonto
*** Film
*** Aufführung
*** Reservierung
** Diese Filter sind eng verbunden
*** Der Anwender muss in der Lage sein, anhand seines ausgewählten Filmes im "Film suchen" die Darstellung des "Aufführung suchen" anzupassen

=== Ablauf

[uml,file="media/Activity_Reservieren.png"]
--

title: Reservation erstellen

(*) --> "Vorstellung selektieren"
--> "Reservation hinzufügen"
if "User selektiert" then
  -->[true] "Übernehme User aus User-Modul"
  -right-> "Sitze selektieren"
else
  -->[false]"Sitze selektieren"
endif

"Sitze selektieren" -> "Reservation speichern"

if "User in Vorstellung vorhanden" then
  -->[true] (*)
else
  -->[false] "User-Feedback"
  --> "Übernehme User aus User-Modul"
endif

--

== Konzepte

=== Filter
Um die Daten der Kinoverwaltung zu filtern, entschieden wir uns dafür, dass jedes Modul seine eigene Filter besizt. Damit die Filter im Code zentral verwaltet werden können, machten wir diese generisch. Es gibt einen Filter für jeden relevanten Filtertyp. Es gibt einen DateFilter, StringFilter, NumberFilter und einen ComplexFilter, wobei letzterer nach Werten von anderen Modulen filtern kann. 

[uml,file="media/filter.png"]
--

interface IFilter<T> {
    bool IsEnalbed
    string Label
    bool Check(T data)
}

class StringFilter<T> {
    string Text
}
class NumberFilter<T> {
    int Number
}
class DateFilter<T> {
    DateTime StartDate
    DateTime EndtDate
}
class ComplexFilter<T, TM : IModule> {
    TM Module
}

IFilter <|.down. StringFilter
IFilter <|.down. NumberFilter
IFilter <|.down. DateFilter
IFilter <|.down. ComplexFilter

--

Dieser Modul-übergreifender Filter ist nötig, damit man die Reservationen einer Person von einem bestimmen Film ansehen kann. Die Module können über den FilterConfigurator ihren Filter konfigurieren. Sie können zum Beispiel einen Stringfilter für den Filmnamen, einen Numberfilter für die ID und einen DateFilter für das Präsentationsdatum anfordern. Dem Filter wird zusätzlich die Liste mit den zu filternden Daten mitgegeben. Beim ComplexFilter wird angegeben, nach welcher Liste im anderen Modul gefiltert werden muss. Zusätzlich wird angegeben welche Liste im eigenen Modul den werten des anderen Modules entsprechen müssen. Der Filter und die Liste können dynamisch im GUI angezeigt werden und sind einfach erweiterbar. Allgemein benötigt man als Entwickler nur wenige Minuten um einen Filter hinzuzufügen, welcher direkt verwendet und im GUI angezeigt wird. 

[uml,file="media/filterConfigurator.png"]
--

interface IFilterConfigurator<T> {
    IFilterConfigurator StringFilter(string label, params Func<T, string>[] valueToCompareTo)
    IFilterConfigurator NumberFilter(string label, params Func<T, int>[] valueToCompareTo)
    IFilterConfigurator DateFilter(string label, params Func<T, DateTime?>[] valueToCompareTo)
    IFilterConfigurator ComplexFilter<TM>(TM module, Func<TM, IEnumerable<T>> valueToCompareTo)
}

class FilterConfigurator<T> {
    ObservableColletion<StringFilter> StringFilters
    ObservableColletion<NumberFilter> NumberFilters
    ObservableColletion<DateFilter> DateFilters
    ObservableColletion<ComplexFilter> ComplexFilters
}

FilterConfigurator .down.|> IFilterConfigurator

--

Wir haben dieses Konzept hauptsächlich für das einfache Anwenden erstellt. Der Entwickler kann ohne viel Aufwand seinen Filter verändern oder sogar eine neue Art von Filter hinzufügen. Ausserdem sind die Filter auf sich gestellt einfach zu testen. Hier ein Beispiel aus dem UserModule.

[source, csharp]
--
    public UserModule()
    {
    	UserFilterConfigurator
        .StringFilter("Name", u => u.Name)
	.StringFilter("Phone", u => u.PhoneNumber)
	.NumberFilter("ID", u => u.UserId);

	UserFilterConfigurator.FilterChanged += (sender, e) => FilterChanged();
    }
--