Dokumentation
=============
Alain Keller, Pascal Honegger und Seraphin Rihm
Version 1.2, 05.07.2016
:toc:

Alle Folgenden Anwendungsfälle sind in der Kategorie Primär solange nicht speziell angegeben. 



= Vorstellung anhand Film finden
=== Beschreibung
Als Kunde möchte ich alle Vorstellungen zu einem Film einsehen können

=== Vorbedingungen
* Das Programm ist gestartet
* Film mit Vorstellung existiert

=== Aktion
. Film suchen anwählen
.. Filmsuche öffnet sich
.. Film suchen
.. Film selektieren
.. Vorstellungen anzeigen wählen
. Korrekte Vorstellung des Filmes wird geladen
Vorstellung suchen) as Vor

[uml]
--
title: Ziel: Vorstellung eines Filmes anzeigen

:User: as User

rectangle System {
    (Vorstellung suchen) as Vor
    
    note right of Vor : Film selektiert
    
    User -right-> Vor
}
--

=== Nachbedingung
Erfolg: Korrekte Vorstellungen werden angezeigt

Fehlschlag: Falsche Daten werden angezeigt

=== Invarianten
Keine veränderten Daten

=== Akteuere
Angestellter, Client

=== Auslösendes Ereignis
User möchte eine Vorstellung finden



= Vorstellung anhand Datum finden
=== Beschreibung
Als Kunde möchte ich alle Vorstellungen zu einem Film einsehen können

=== Vorbedingungen
* Das Programm ist gestartet
* Vorstellung am korrekten Datum existiert

=== Aktion
. Vorestellung suchen anwählen
.. Vorestellung suchen öffnet sich
.. Datum eingeben
. Korrekte Vorstellungen werden geladen

[uml]
--
title: Ziel: Vorstellung an einem Datum anzeigen

:User: as User

rectangle System {
    (Vorstellung suchen) as Vor
    
    note right of Vor : Datum im GUI eingetragen
    
    User -right-> Vor
}
--

=== Nachbedingung
Erfolg: Korrekte Vorstellungen werden angezeigt

Fehlschlag: Falsche Daten werden angezeigt

=== Invarianten
Keine veränderten Daten

=== Akteuere
Angestellter, Client

=== Auslösendes Ereignis
User möchte eine Vorstellung finden



= Freie Plätze einer Vorstellung anzeigen
=== Beschreibung
Als Kunde möchte ich alle alle freien Plätze erfahren, damit ich einen reservieren kann

=== Vorbedingungen
* Das Programm ist gestartet
* Vorstellung mit freien Sitzen existiert

=== Aktion
. Vorstellung suchen anwählen
.. Vorstellung suchen öffnet sich
.. Vorstellung mit freien Sitzplätzen selektieren
.. Platz reservieren anwählen
... Platz reservieren öffnet sich
... Freie Plätze sind ersichtlich
.... Besetzte Plätze sind markiert
.... Selektierte Plätze sind hervorgehoben

[uml]
--
title: Ziel: Reservationen einer Vorstellung anzeigen

:User: as User

rectangle System {
    (Reservation suchen) as Res
    
    note right of Res : Vorstellung selektiert
    
    User -right-> Res
}
--

=== Nachbedingung
Erfolg: Korrekte Vorstellungen werden angezeigt

Fehlschlag: Falsche Daten werden angezeigt

=== Invarianten
Keine veränderten Daten

=== Akteuere
Angestellter, Client

=== Auslösendes Ereignis
User möchte eine Vorstellung finden



= Freie Plätze einer Vorstellung reservieren
=== Beschreibung
Als Kunde möchte ich eine Vorstellung reservieren können

=== Vorbedingungen
* UseCase "Freie Plätze einer Vorstellung anzeigen"

=== Aktion
. User auswählen
.. Wird in ReservationsModul übernommen
. Freie Sitzplätze sind ersichtlich
.. Anzahl zu reservierenden Plätze eingeben
.. Sitzplätze auswählen
. Reservation speichern

[uml]
--
title: Ziel: Reservationen einer Vorstellung anzeigen

:User: as User

rectangle System {
    (Freie Sitzplätze reservieren) as UseUser
    
    note right of UseUser : User auswählen
    
    User -right-> UseUser
}
--

=== Nachbedingung
Erfolg: Korrekte Vorstellungen werden angezeigt
Fehlschlag: Falsche Daten werden angezeigt

=== Invarianten
Keine veränderten Daten

=== Akteuere
Angestellter, Client

=== Auslösendes Ereignis
User möchte eine Vorstellung finden



= Reservierung stornieren
=== Beschreibung
Als Kunde möchte seine Reservation stornieren

=== Vorbedingungen
* Das Programm ist gestartet
* UseCase "Vorstellung reservieren"

=== Aktion
. Reservationen anzeigen anwählen
.. Reservationen anzeigen öffnet sich
.. Gewünschte Reservation suchen
.. Reservation über "Reservation stornieren" stornieren
. Reservation ist storniert

[uml]
--
title: Ziel: Reservierung stornieren

:User: as User

rectangle System {
    (Reservation stornieren) as UseUser
    
    note right of UseUser : Reservation auswählen
    
    User -right-> UseUser
}
--

=== Nachbedingung
Erfolg: Die Reservation wurde erfolgreich storniert und die Plätze sind wieder freigegeben
Fehlschlag: Die Plätze sind immer noch vom Kunden reserviert

=== Invarianten
Vorstellung

=== Akteuere
User, Client

=== Auslösendes Ereignis
Ein User möchte seine Reservation stornieren.



= Reservierung anpassen
=== Beschreibung
Ein Kunde möchte seine Reservierung anpassen. Er möchte zwei weitere Sitze Reservieren

=== Vorbedingungen
* Das Programm ist gestartet
* Der Kunde ist erfasst
* Kunde hat eine Reservation gemacht

=== Aktion
. Reservationen des Kundes anzeigen
.. Reservation auswählen
.. Reservation wird angezeigt
. Sitze hinzufügen
.. Speichern

[uml]
--
title: Ziel: Vorstellung an einem Datum anzeigen

:User: as User

rectangle System {
    (Sitze hinzufügen) as UseUser
    
    note right of UseUser : Reservation des User ist ausgewählt
    
    User -right-> UseUser
}
--

=== Nachbedingung
Erfolg: Die Anpassung war erfolgreich, der Reservation des Kundens wurden zwei weitere Sitze hinzugefügt
Fehlschlag: Es war nicht möglich die Reservation anzupassen. Die zwei Sitze wurden nicht reserviert

=== Invarianten
Keine veränderten Daten

=== Akteuere
User, Client

=== Auslösendes Ereignis
Ein Kunde möchte seine Reservation ändern.



= Film anhand Namen suchen
=== Beschreibung
Als Kunde möchte ich einen Film finden können, von welchem ich nur den Namen kenne.

=== Vorbedingungen
* Das Programm ist gestartet
* Gewünschter Film ist im System vorhanden

=== Aktion
. Film suchen anwählen
.. Filmsuche öffnet sich
.. Namen eingeben
.. Film suchen
. Gesuchter Film wird gefunden

[uml]
--
title: Ziel: Filme filtern

:User: as User

rectangle System {
    User -up-> (Film suchen)
}
--

=== Nachbedingung
Erfolg: Der korrekte Film wird gefunden
Fehlschlag: Falsche Daten werden angezeigt

=== Invarianten
Keine veränderten Daten

=== Akteuere
User, Client

=== Invarianten
Keine 

=== Auslösendes Ereignis
Ein neuer Film soll im Kino angeboten werden



= Film erstellen
=== Beschreibung
Als Kino möchte ich in der Lage sein, neue Filme zu erfassen.

=== Vorbedingungen
* Das Programm ist gestartet

=== Aktion
. Film erfassen anwählen
.. Film erfassen öffnet sich
.. Daten für den Film eintragen
.. Dialog bestätigen
. Film ist erfasst

[uml]
--
title: Ziel: Film erstellen

:User: as User

rectangle System {
    User -up-> (Film erstellen)
}
--

=== Nachbedingung
Erfolg: Film korrekt erfasst. Kann in anderen Modulen verwendet werden.
Fehlschlag: Daten wurden nicht korrekt gespeichert

=== Invarianten
Alle Daten ausser Säle und Sitzplätze

=== Akteuere
User, Client

=== Auslösendes Ereignis
User will neun Saal erfassen



= Saal erfassen
=== Beschreibung
Als User möchte ich einen neuen Saal mit Sitzplätzen erfassen

=== Vorbedingungen
* Das Programm ist gestartet

=== Aktion
. Saal Erfassungsmaske öffnen
.. Erfassungsmaske öffnet sich
.. User erstellt einen neuen Saal
.. User erstellt Sitzplätze für neuen Saal
. Die Daten werden auf der Datenbank geupdatet

[uml]
--
title: Ziel: Neuen Saal erfassen

:User: as User

rectangle System {
    User -right-> (Saal erfassen)
}
--

=== Nachbedingung
Erfolg: Die Änderungen werden korrekt übernommen und sind beim nächsten logon immernoch vorhanden
Fehlschlag: Daten wurden nicht korrekt gespeichert

=== Invarianten
Alle Daten ausser Säle und Sitzplätze

=== Akteuere
User, Client

=== Auslösendes Ereignis
User will neun Saal erfassen



= Saal / Sitzplätze bearbeiten
=== Beschreibung
Als User möchte ich erfasste Säle und die sitzplätze eines Saales bearbeiten können

=== Vorbedingungen
* Das Programm ist gestartet
* Es sind Säle und Sitzplätze erfast

=== Aktion
. Bearbeitungsmaske öffnen
.. Bearbeitungsmaske öffnet sich
.. Der User wählt einen Saal aus
.. Der User kann nun diesen Saal und seine Sitzplätze bearbeiten
. Die Daten werden auf der Datenbank geupdatet

[uml]
--
title: Ziel: Saal und Sitzplätze editieren

:User: as User

rectangle System {
    (Saal editieren) as EditRoom
    
    note right of EditRoom : Saal ausgewählt
    
    User -> EditRoom
    EditRoom -down-> (Sitzplätze editieren)
}
--

=== Nachbedingung
Erfolg: Die Änderungen werden korrekt übernommen und sind beim nächsten logon immernoch vorhanden
Fehlschlag: Daten wurden nicht korrekt gespeichert

=== Invarianten
Alle Daten ausser Säle und Sitzplätze

=== Akteuere
User, Client

=== Auslösendes Ereignis
User möchte einen Saal anpassen



= Reservation anhand Kunde finden
=== Beschreibung
Als User möchte ich alle Reservationen eines Kunden finden

=== Vorbedingungen
* Das Programm ist gestartet
* Der Kunde ist erfasst

=== Aktion
. Reservationsfilter asuwählen
.. Reservationsfilterung öffnet sich
.. User gibt Kunden Name oder Telefonnummer ein
. Reservationen des Kundes werden zurückgegeben
. Reservation selektieren für mehr Detais

[uml]
--
title: Ziel: Reservation von Kunde finden

:User: as User

rectangle System {
    (Reservation suchen) as Res
    
    note right of Res : User ausgewählt
    
    User -> Res
}
--

=== Nachbedingung
Erfolg: Alle Reservationen des Kundes werden angzeigt
Fehlschlag: Reservationen werden nicht angezeigt

=== Invarianten
Keine veränderten Daten

=== Akteuere
User, Client

=== Auslösendes Ereignis
User möchte Reservationen von Kude finden